apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: tchanela/polished:ViaDora
        ports:
        - containerPort: 80